-- MySQL Script generated by MySQL Workbench
-- 07/07/15 23:04:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `University` ;

-- -----------------------------------------------------
-- Schema University
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `University` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `University` ;

-- -----------------------------------------------------
-- Table `University`.`Faculties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `University`.`Faculties` ;

CREATE TABLE IF NOT EXISTS `University`.`Faculties` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `University`.`Departments` ;

CREATE TABLE IF NOT EXISTS `University`.`Departments` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `FacultyId` INT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `FK_Department_Faculty_idx` (`FacultyId` ASC)  COMMENT '',
  CONSTRAINT `FK_Department_Faculty`
    FOREIGN KEY (`FacultyId`)
    REFERENCES `University`.`Faculties` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `University`.`Professors` ;

CREATE TABLE IF NOT EXISTS `University`.`Professors` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `DepartmentId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `FK_Professors_Department_idx` (`DepartmentId` ASC)  COMMENT '',
  CONSTRAINT `FK_Professors_Department`
    FOREIGN KEY (`DepartmentId`)
    REFERENCES `University`.`Departments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `University`.`Titles` ;

CREATE TABLE IF NOT EXISTS `University`.`Titles` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`ProfessorsTitles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `University`.`ProfessorsTitles` ;

CREATE TABLE IF NOT EXISTS `University`.`ProfessorsTitles` (
  `ProfessorId` INT NOT NULL COMMENT '',
  `TitleId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ProfessorId`, `TitleId`)  COMMENT '',
  INDEX `FK_ProfessorsTitles_Titles_idx` (`TitleId` ASC)  COMMENT '',
  CONSTRAINT `FK_ProfessorsTitles_Professors`
    FOREIGN KEY (`ProfessorId`)
    REFERENCES `University`.`Professors` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ProfessorsTitles_Titles`
    FOREIGN KEY (`TitleId`)
    REFERENCES `University`.`Titles` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `University`.`Courses` ;

CREATE TABLE IF NOT EXISTS `University`.`Courses` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `DepartmentId` INT NOT NULL COMMENT '',
  `ProfessorId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `FK_Courses_Departments_idx` (`DepartmentId` ASC)  COMMENT '',
  INDEX `FK_Courses_Professors_idx` (`ProfessorId` ASC)  COMMENT '',
  CONSTRAINT `FK_Courses_Departments`
    FOREIGN KEY (`DepartmentId`)
    REFERENCES `University`.`Departments` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Courses_Professors`
    FOREIGN KEY (`ProfessorId`)
    REFERENCES `University`.`Professors` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `University`.`Students` ;

CREATE TABLE IF NOT EXISTS `University`.`Students` (
  `Id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Name` VARCHAR(45) NOT NULL COMMENT '',
  `FacultyId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Id`)  COMMENT '',
  INDEX `FK_Students_Faculties_idx` (`FacultyId` ASC)  COMMENT '',
  CONSTRAINT `FK_Students_Faculties`
    FOREIGN KEY (`FacultyId`)
    REFERENCES `University`.`Faculties` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `University`.`StudentsCourses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `University`.`StudentsCourses` ;

CREATE TABLE IF NOT EXISTS `University`.`StudentsCourses` (
  `StudentId` INT NOT NULL COMMENT '',
  `CourseId` INT NOT NULL COMMENT '',
  PRIMARY KEY (`StudentId`, `CourseId`)  COMMENT '',
  INDEX `FK_StudentsCourses_Courses_idx` (`CourseId` ASC)  COMMENT '',
  CONSTRAINT `FK_StudentsCourser_Students`
    FOREIGN KEY (`StudentId`)
    REFERENCES `University`.`Students` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_StudentsCourses_Courses`
    FOREIGN KEY (`CourseId`)
    REFERENCES `University`.`Courses` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
